name: Scheduled Python Script

on:
    schedule:
        - cron: "*/5 * * * *" # every 5 minutes (for testing)
    workflow_dispatch: # allows manual triggering

jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install dependencies
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  pip install -r requirements.txt

            - name: Run script
              run: |
                  source venv/bin/activate
                  python hello.py
